### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by there-is-a-bug** [JasonJerome/Pointer-meter-reading-algorithm-by-Python#3]
您好，我的本科毕设题目与您的类似，看了一下您的代码，冒昧问一下您的代码思路是怎样的呢？然后训练集（train.txt）后面的参数是取的图片框嘛？

**Comment by JasonJerome** [comment]
我的代码的思路是这样的：我通过训练好的模型抓取出相应的指针式仪表的图片（这一步主要是为了降低复杂环境对识别的影响），然后使用OpenCV对提取出来的图片进行处理

**Comment by there-is-a-bug** [comment]
谢谢解答，那请问train.txt后面的5个参数是什么呢

**Comment by ghost** [comment]
> 我的代码的思路是这样的：我通过训练好的模型抓取出相应的指针式仪表的图片（这一步主要是为了降低复杂环境对识别的影响），然后使用OpenCV对提取出来的图片进行处理

可以问下opencv读数的代码部分是哪些吗，我计划通过语义分割出指针和刻度进行读数，目前困在如何处理分割得到的图片，希望能参考下您的思路

**Comment by JasonJerome** [comment]
在读数部分的话我是用霍夫变换查找相关直线，主要是开始刻度和结束刻度以及指针，霍夫变换会返回相应的角度，只要区分不同象限进行计算即可，但是这样的方法可能不够鲁棒。我之前看相关的论文，有通过语义分割找出相应的标志物的位置（可能是boundingBox等），然后根据标志物的位置来进行计算，但我没有进行深入研究

**Comment by JasonJerome** [comment]
> > 我的代码的思路是这样的：我通过训练好的模型抓取出相应的指针式仪表的图片（这一步主要是为了降低复杂环境对识别的影响），然后使用OpenCV对提取出来的图片进行处理
> 
> 可以问下opencv读数的代码部分是哪些吗，我计划通过语义分割出指针和刻度进行读数，目前困在如何处理分割得到的图片，希望能参考下您的思路

在读数部分的话我是用霍夫变换查找相关直线，主要是开始刻度和结束刻度以及指针，霍夫变换会返回相应的角度，只要区分不同象限进行计算即可，但是这样的方法可能不够鲁棒。我之前看相关的论文，有通过语义分割找出相应的标志物的位置（可能是boundingBox等），然后根据标志物的位置来进行计算，但我没有进行深入研究
